---
title: "Grand Canyon QAQC for I&M Data"
author: "Alexandra Lalor"
date: "2024-11-06"
output:
  html_document:
    theme: readable
    highlight: 
    toc: yes
    toc_depth: 3
    toc_float:
      smooth_scroll: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# Install packages (if needed)
# install.packages("tidyverse")
# install.packages("Rtools")
```

# BEFORE STARTING

### Load Packages

```{r}
# Load packages
library(tidyverse)
library(writexl)
library(dplyr)
library(knitr)
```

### Adjust File Paths

Make sure to update file paths to be specific for your data.

```{r}
# Identify working directory (specifically user name)
getwd()

# Load in data and name them based on file path
# Change file path based on user name!
path_data <- "C:/Users/alalor.NPS/OneDrive - DOI/Desktop/R/GRCA/data/qaqc/2024/"
path_errors <- "C:/Users/alalor.NPS/OneDrive - DOI/Desktop/R/GRCA/output/errors/2024/"
```

### Load Data

```{r}
# Blank data frame for no errors
errors_blank <- data.frame("SavedQuery" = "","MacroPlot.Name" = "","Date" = "","Error" = "No Error", "Comment" = "")
```

```{r}
# Load in data
Fuels1000_all <- read.csv(paste0(path_data, "GRCA_FMH_2024_Surface Fuels - 1000Hr_XPT.csv"))
FuelsDuffLitt_all <- read.csv(paste0(path_data, "GRCA_FMH_2024_Surface Fuels - Duff_Litter_XPT.csv"))
Trees_all <- read.csv(paste0(path_data, "I&M_Trees - Individuals (metric)_XPT.csv"))
#PostBurn_all <- read.csv(paste0(path_data, "Post Burn Severity_XPT.csv"))

# PostBurn_all <- read.csv("C:/Users/allie/OneDrive/Desktop/R Projects/GRCA/data/qaqc/AllYears/I&M_Post Burn Severity_XPT.csv")
```
