---
title: "QAQC_FMH_GRCA"
output: html_document
date: "2024-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# Install packages (if needed)
install.packages("tidyverse")
```

## R Markdown

press ctrl+alt+i to create a code block

# BEFORE STARTING

```{r}
# Load packages
library(tidyverse)
library(writexl)

# Identify working directory (specifically user name)
getwd()

# Load in data and name them based on file path
# Change file path based on user name!
#data_path <- "C:/Users/alalor.NPS/Desktop/R/GRCA/data/data_qaqc/2024/ORIGINALS/"
data_path <- "C:/Users/alalor.NPS/Desktop/R/GRCA/data/data_qaqc/2024/"
errors_path <- "C:/Users/alalor.NPS/Desktop/R/GRCA/data/data_errors/2024/"
```

# SURFACE FUELS - 1000HR CWD

```{r}
#### Load in data ####
Fuels1000_all <- read.csv(paste0(data_path, "Surface Fuels - 1000Hr_XPT.csv"))

## NEED TO MAKE SURE COLUMNS HAVE SIMILAR OUTPUT!! I'VE GOTTEN INCONSISTENT RESULTS
## EG BLANKS VS NA, CAPITALIZED VS NOT, ETC...
Fuels1000_all$Visited[Fuels1000_all$Visited==""] <- NA

Fuels1000_all <- Fuels1000_all %>%
  mutate(Visited = toupper(Visited)) %>%
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(MacroPlot.Name, sep = " ", into = c("MonitoringType", "Plot"), remove = FALSE)

# Filter for only data
Fuels1000_data <- Fuels1000_all %>%
  filter(is.na(Visited))

# Filter for only headers
Fuels1000_header <- Fuels1000_all %>%
  filter(!is.na(Visited))

# Blank data frame for no errors
no_errors <- data.frame("SavedQuery" = "","MacroPlot.Name" = "","Date" = "","Error" = "No Error","Fixed?" = "","Explanation" = "","Person" = "")
```

## Fuel 1000 DecayClass

This code will check if decay class values are correct.

```{r}
# Set parameters
saved_query <- "Fuel 1000 DecayClass"
error_message <- "Decay Class"
column_data <- Fuels1000_data$DecayCl
valid_values <- c(3,4)

# Identify errors
errors_DecayCl <- Fuels1000_data %>%
  mutate("SavedQuery" = saved_query,
         "Error" = paste(error_message, "=", column_data),
         "Fixed?" = "",
         "Explanation" = "",
         "Person" = "") %>%
  filter(!column_data %in% valid_values) %>%
  select(c("SavedQuery", "MacroPlot.Name", "Date", "Error", "Fixed?","Explanation","Person"))

# If no errors, add "No Errors" to existing data frame
if (nrow(errors_DecayCl) == 0) {
  errors_DecayCl <- no_errors %>%
    mutate(SavedQuery = saved_query)
} else {
  errors_DecayCl <- errors_DecayCl
}
```
